-- DAY_WAVE_FUNCTION_COLUMN
JOINPLAYERFUNCTION			= 1;
DETACHPLAYERFUNCTION		= 2;
PRESTARTROUNDFUNCTION		= 3;
STARTROUNDFUNCTION			= 4;
BATTLEUPDATEFUNCTION		= 5;
ENDROUNDFUNCTION			= 6;
ROUNDTIMEOUTFUNCTION		= 7;
TIMEOUTFUNCTION				= 8;
INSTALLFUNCTION				= 9;
UNINSTALLFUNCTION			= 10;
USEFUNCTION					= 11;
DAMAGEOBJECTFUNCTION		= 12;
DESTROYOBJECTFUNCTION		= 13;
ENTERTRIGGERFUNCTION		= 14;
LEAVETRIGGERFUNCTION		= 15;
KEYPROCFUNCTION				= 16;
ANNIHILATEAIGROUPFUNCTION	= 17;
GAMEOBJUSEFUNCTION			= 18;
KILLPLAYERFUNCTION			= 19;
RESPAWNPLAYERFUNCTION		= 20;

USER_COUNT_MAX		= 4
RESPAWN_MAX 		= 9
RESPAWN_INIT		= 3
END_ROUND 			= 20

-- DAY_WAVE_LIST_COLUMN
DAY_NUMBER			= 1
WAVE_NUMBER			= 2
WAVE_GOAL			= 3
WAVE_TIME			= 4
WAVE_KILLCOUNT		= 5
WAVE_FUNCTION		= 6

-- Score
SCORE_KILL_RAPTER			= 50
SCORE_KILL_ACID				= 40
SCORE_KILL_STING			= 60
SCORE_KILL_ELITE			= 60
SCORE_KILL_TANK				= 70
SCORE_KILL_BOSS				= 1000

SCORE_MISSION_DEMOLITION_DESTROY	= 200
SCORE_MISSION_DEMOLITION_DAMAGE_1	= 10		-- 1% 데미지당
SCORE_MISSION_DEMOLITION_DAMAGE_30	= 100
SCORE_MISSION_DEMOLITION_DAMAGE_50	= 300
SCORE_MISSION_DEMOLITION_DAMAGE_100	= 500

SCORE_MISSION_RECOVERY_COUNT_1		= 200		-- 오브젝트 회수시
SCORE_MISSION_RECOVERY_COUNT_2		= 200		-- 한 데이안에서 여러번 회수시 1count score+2count score
SCORE_MISSION_RECOVERY_COUNT_3		= 300		-- 한 데이안에서 여러번 회수시 1count score+3count score

SCORE_MISSION_DEFFENCE_SUCCESS		= 500

SCORE_MISSION_BOSS_KILL				= 2000

SCORE_WAVE_CLEAR					= 300
SCORE_WAVE_REMAIN_TIME				= 3			-- 한 웨이브를 3분내로 클리어했을때 3분까지 남은 시간 1초당
SCORE_WAVE_NO_USE_LIFE				= 100		-- 라이프 소진하지 않고 클리어시
SCORE_WAVE_NO_USE_SP				= 100		-- SP 소진하지 않고 클리어시

SCORE_DAY_CLEAR						= 1000
SCORE_DAY_REMAIN_TIME				= 5			-- 한 데이를 10분내로 클리어했을때 10분까지 남은 시간 1초당
SCORE_DAY_NO_USE_LIFE				= 500		-- 라이프 소진하지 않고 클리어시

SCORE_GAME_CLEAR					= 5000
SCORE_GAME_REMAIN_TIME				= 10		-- 한 게임을 60분내로 클리어했을때 60분까지 남은 시간 1초당
SCORE_GAME_REMAIN_LIFE				= 200		-- 라이프가 한개 이상일때 라이프수만큼
SCORE_GAME_NO_USE_LIFE				= 2000		-- 라이프 소진하지 않고 클리어시
SCORE_GAME_DINO_KILL_10				= 100
SCORE_GAME_DINO_KILL_50				= 500
SCORE_GAME_DINO_KILL_100			= 1000
SCORE_GAME_DINO_KILL_200			= 2000
SCORE_GAME_DINO_KILL_300			= 3000


SKILL_DAMAGEUP_DURATION				= 20
SKILL_SPEEDUP_DURATION				= 20

-- 설치 오브젝트
SupplyBaseHP						= 2006009015
SupplyBaseAMMO						= 2006009016
RecoveryObject_DNA					= 2006009017
BossBombDummy						= 2006009019
BossBomb							= 2006009020

OBJECT_ATTRIBUTE = {
	COLLECT = 0,
	DESTROY = 1,
	DEFENSE = 2,
}

-- AI Group
AI_GROUP = {
	AG_NONE							= 0,
	Basic_A							= 1,
	Basic_B							= 2,
	Basic_C							= 3,
	Basic_D							= 4,
	Basic_E							= 5,
	Eli_A							= 6,
	Eli_B							= 7,
	Eli_C							= 8,
	Eli_D							= 9,
	Trg_1							= 10,
	Trg_2							= 11,
	Trg_3							= 12,
	Trg_4							= 13,
}

-- 사용 효과 정리
EffectList = {
	Effect_SupplyBaseHP = {
		EffectCount = 1,
		Effects = {
			{EFFECT_TYPE.HP, nil, 20},
		}
	},
	Effects_SupplyBaseAMMO = {
		EffectCount = 1,
		Effects = {
			{EFFECT_TYPE.AMMO, WEAPON_USAGE.PRIMARY, 50},
		}
	},
	Effects_SUPPLYBASE_1 = {
		EffectCount = 3,
		Effects = {
			{EFFECT_TYPE.HP, nil, 10},
			{EFFECT_TYPE.AMMO, WEAPON_USAGE.PRIMARY, 50},
			{EFFECT_TYPE.AMMO, WEAPON_USAGE.SECONDARY, 50},
		}
	},
	Effects_SUPPLYBASE_2 = {
		EffectCount = 3,
		Effects = {
			{EFFECT_TYPE.HP, nil, 10},
			{EFFECT_TYPE.AMMO, WEAPON_USAGE.PRIMARY, 100},
			{EFFECT_TYPE.AMMO, WEAPON_USAGE.SECONDARY, 100},
		}
	},
	Effects_SUPPLYBASE_3 = {
		EffectCount = 3,
		Effects = {
			{EFFECT_TYPE.HP, nil, 12},
			{EFFECT_TYPE.AMMO, WEAPON_USAGE.PRIMARY, 60},
			{EFFECT_TYPE.AMMO, WEAPON_USAGE.SECONDARY, 60},
		}
	},
	Effects_SUPPLYBASE_4 = {
		EffectCount = 3,
		Effects = {
			{EFFECT_TYPE.HP, nil, 15},
			{EFFECT_TYPE.AMMO, WEAPON_USAGE.PRIMARY, 100},
			{EFFECT_TYPE.AMMO, WEAPON_USAGE.SECONDARY, 100},
		}
	},
	Effects_DROP_PLUS = {
		EffectCount = 1,
		Effects = {
			{EFFECT_TYPE.DROP_PLUS, nil, 20},
		}
	},
}

-- 야전상점 아이템
FS_LIFE_PLUS					= 2101134000
FS_SP_BOOST						= 2100135000
FS_SP_PLUS						= 2101136000
FS_REVIVAL_NORMAL				= 2101137000
FS_REVIVAL_TEAM					= 2101138001
FS_REVIVAL_ALL					= 2101139000
FS_DROP_PLUS					= 2100140000

-- 제압미션 맵 ID
STAGE_TYPE_DOMINATION			= 11
STAGE_SLOT_MODE_NORMAL			= 0
STAGE_ORD_DEADTOWN				= 43
STAGE_ORD_DEADTOWN2				= 51
STAGE_ORD_DEADTOWN3				= 52
STAGE_ORD_DEADTOWN4				= 53

STAGE_ID_DEADTOWN				= STAGE_ORD_DEADTOWN + (STAGE_TYPE_DOMINATION*16777216) + (STAGE_SLOT_MODE_NORMAL*65536)
STAGE_ID_DEADTOWN2				= STAGE_ORD_DEADTOWN2 + (STAGE_TYPE_DOMINATION*16777216) + (STAGE_SLOT_MODE_NORMAL*65536)
STAGE_ID_DEADTOWN3				= STAGE_ORD_DEADTOWN3 + (STAGE_TYPE_DOMINATION*16777216) + (STAGE_SLOT_MODE_NORMAL*65536)
STAGE_ID_DEADTOWN4				= STAGE_ORD_DEADTOWN4 + (STAGE_TYPE_DOMINATION*16777216) + (STAGE_SLOT_MODE_NORMAL*65536)
