----------
-- 상수 값
----------
TEAM = {
	RED		= 0,
	BLUE	= 1,
	BOTH	= 2,
	COUNT	= 2,
	DRAW	= 2
}
END_TYPE = {
	TYPE_NONE			= 0,
	TIMEOUT				= 1,
	BOMBFIRE			= 2,
	UNINSTALL			= 3,
	ALLDEATH			= 4,
	GENERATOR_DESTROY	= 5,			-- 파괴 미션 오브젝트 파괴
	DEFENCE_DESTROY		= 6,			-- 방어 미션 오브젝트 파괴
	TUTORIAL_COMPLETE	= 7,			-- 튜토리얼 임무 완료
	MAX_KILL			= 8,			-- 데스매치에서 목표 킬카운트 달성
}

CHARA_DEATH_ENEMY_STATE = {
	NONE				= 0,
	DEFENCE				= 1,
	ESCAPE				= 2,
	SAVER				= 3,
}

CHARA_DEATH_MY_STATE = {
	NONE				= 0,
	ASSIST				= 1,
}

UNKNOWN_SLOT_IDX		= -1
SLOT_MAX_COUNT			= 16
SLOT_IDX_START			= 0
SLOT_IDX_END			= 15

SLOT_TYPE_USER			= 0
SLOT_TYPE_AI			= 1

EVENT_ERROR_SUCCESS			= 0
EVENT_ERROR_FAIL			= -1
EVENT_ERROR_EVENT_BUY_GOODS_NOT_ALLOWED		= 0x800010D6
EVENT_ERROR_EVENT_USE_ITEM_NOT_ALLOWED		= 0x800010D7

-- enum GAME_KEY_MAP
GAME_KEY_MAP_COUNT		= 0;
GAME_KEY_MAP = {}
GAME_KEY_MAP.VERSION 			= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.LEFT 				= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.RIGHT 				= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.FORWARD 			= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.BACKWARD 			= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.JUMP 				= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.FOOTSTEP 			= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.CROUCH 			= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.TURNBACK 			= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;

GAME_KEY_MAP.ATTACK 			= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.SUBFUNC 			= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.RELOAD 			= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;

GAME_KEY_MAP.CHANGEWEAPON 		= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.CHANGEWEAPON_1 	= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.CHANGEWEAPON_2 	= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.CHANGEWEAPON_3 	= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.CHANGEWEAPON_4 	= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.CHANGEWEAPON_5 	= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.CHANGEWEAPON_6 	= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.CHANGEWEAPON_QUICK = GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.CHANGEWEAPON_PREV 	= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.CHANGEWEAPON_NEXT 	= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.CHANGEWEAPON_7 	= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.CHANGEWEAPON_8 	= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.CHANGEWEAPON_9 	= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.DROP 				= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;


GAME_KEY_MAP.SHOWSCORE 			= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.TOGGLE_MAP 		= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.MINIMAP_ENLARGE 	= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.MINIMAP_REDUCTION 	= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.CHAT 				= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.CHAT_ALL 			= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.CHAT_TEAM 			= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.CHAT_HISTORY 		= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.VOICECHAT 			= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.RADIOMESSAGE1 		= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.RADIOMESSAGE2 		= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.RADIOMESSAGE3 		= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.SPECIALACTION 		= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.MOUSE_SENS_UP 		= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.MOUSE_SENS_DOWN 	= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.SCREENSHOT 		= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;

GAME_KEY_MAP.CHAT_CLAN 			= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;

GAME_KEY_MAP.WEAPON_EXTENSION 	= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;

GAME_KEY_MAP.VIDEOCAPTURE 		= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.INGAME_SHOP 		= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;
GAME_KEY_MAP.SPECIAL_MISSION	= GAME_KEY_MAP_COUNT; GAME_KEY_MAP_COUNT = GAME_KEY_MAP_COUNT + 1;

-- enum EFFECT_TYPE
EFFECT_TYPE_COUNT	= 0;
EFFECT_TYPE = {}
EFFECT_TYPE.NONE		= EFFECT_TYPE_COUNT; EFFECT_TYPE_COUNT = EFFECT_TYPE_COUNT + 1;
EFFECT_TYPE.AMMO		= EFFECT_TYPE_COUNT; EFFECT_TYPE_COUNT = EFFECT_TYPE_COUNT + 1;
EFFECT_TYPE.HP			= EFFECT_TYPE_COUNT; EFFECT_TYPE_COUNT = EFFECT_TYPE_COUNT + 1;
EFFECT_TYPE.DAMAGE		= EFFECT_TYPE_COUNT; EFFECT_TYPE_COUNT = EFFECT_TYPE_COUNT + 1;
EFFECT_TYPE.SPEED		= EFFECT_TYPE_COUNT; EFFECT_TYPE_COUNT = EFFECT_TYPE_COUNT + 1;
EFFECT_TYPE.GET_ITEM	= EFFECT_TYPE_COUNT; EFFECT_TYPE_COUNT = EFFECT_TYPE_COUNT + 1;
EFFECT_TYPE.DROP_PLUS	= EFFECT_TYPE_COUNT; EFFECT_TYPE_COUNT = EFFECT_TYPE_COUNT + 1;


-- enum WEAPON_USAGE_TYPE
WEAPON_USAGE_TYPE_COUNT	= 0;
WEAPON_USAGE = {}
WEAPON_USAGE.UNKNOWN	= -1;
WEAPON_USAGE.ALL		= WEAPON_USAGE.UNKNOWN;
WEAPON_USAGE.PRIMARY	= WEAPON_USAGE_TYPE_COUNT; WEAPON_USAGE_TYPE_COUNT = WEAPON_USAGE_TYPE_COUNT + 1;	--	주무기
WEAPON_USAGE.SECONDARY	= WEAPON_USAGE_TYPE_COUNT; WEAPON_USAGE_TYPE_COUNT = WEAPON_USAGE_TYPE_COUNT + 1;	--	보조무기
WEAPON_USAGE.MELEE		= WEAPON_USAGE_TYPE_COUNT; WEAPON_USAGE_TYPE_COUNT = WEAPON_USAGE_TYPE_COUNT + 1;	--	근접무기
WEAPON_USAGE.THROWING	= WEAPON_USAGE_TYPE_COUNT; WEAPON_USAGE_TYPE_COUNT = WEAPON_USAGE_TYPE_COUNT + 1;	--	투척무기
WEAPON_USAGE.ITEM		= WEAPON_USAGE_TYPE_COUNT; WEAPON_USAGE_TYPE_COUNT = WEAPON_USAGE_TYPE_COUNT + 1;	--	투척 아이템
WEAPON_USAGE.MISSION	= WEAPON_USAGE_TYPE_COUNT; WEAPON_USAGE_TYPE_COUNT = WEAPON_USAGE_TYPE_COUNT + 1;	--	미션 아이템

WEAPON_USAGE.SPECIAL1	= WEAPON_USAGE_TYPE_COUNT; WEAPON_USAGE_TYPE_COUNT = WEAPON_USAGE_TYPE_COUNT + 1;	--	투척무기
WEAPON_USAGE.SPECIAL2	= WEAPON_USAGE_TYPE_COUNT; WEAPON_USAGE_TYPE_COUNT = WEAPON_USAGE_TYPE_COUNT + 1;	--	투척 아이템
WEAPON_USAGE.SPECIAL3	= WEAPON_USAGE_TYPE_COUNT; WEAPON_USAGE_TYPE_COUNT = WEAPON_USAGE_TYPE_COUNT + 1;	--	미션 아이템

-- enum AI_POINT_TYPE
AI_POINT_TYPE_POINT		= 0;	-- AI전 점수
AI_POINT_TYPE_SP		= 1;	-- 제압미션 SP
